### ISSUE TITLE
Does not support split DNS zones

### ISSUE THREAD

**Issue by julijane** [libdns/route53#6]
It is possible in AWS to have split DNS zones, i.e. a different zone presented to the outside world than internally. The internal zones have a flag "PrivateZone" set to true. In my opinion it makes sense to automatically pick the zone which has PrivateZone set to false when multiple zones are available for the given domain name as of course the record needs to be done in the public DNS zone.

It would be awesome if this could be added.

**Comment by seansaleh** [comment]
+1 to this. 
I have a slightly different scenario, I have two zones, one private which covers `example.org` and one public which covers `subdomain.example.org`. I'm trying to issue a cert based on the `subdomain.example.org`, but can't due to this implementation only picking the very first zone it chooses.

Expanding this tool by either ignoring `PrivateZone`'s or by choosing the more precise public zone, or even by allowing the zone to be parametrized would be great!
